### ISSUE TITLE
The style tag is empty at all

### ISSUE THREAD

**Issue by HakS** [kei-ito/esifycss#104]
Hello

As far as I understood this plugin, all happens in the `addStyle` function, so it reads the rules and if this regex is false `if (!(/^\s*@charset/i).test(rule)) {` then it adds the rule

And that's the issue, because I have a CSS in which all the rules are passed by true, therefore no rule is passed on, and therefore the style tag remains empty

![image](https://user-images.githubusercontent.com/1095029/97606994-6736a280-19de-11eb-8db2-2f21c3bc8a54.png)

**Comment by kei-ito** [comment]
You're right, it is a bug. I found esifycss serializes `@charset` to wrong form. I'll fix it in https://github.com/kei-ito/esifycss/pull/105.
Thank you for your report!

**Comment by kei-ito** [comment]
I published v1.4.25 includes the fix. Please check it and open another issue if there's still a problem.
