### ISSUE TITLE
Is acorn-dynamic-import still needed?

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [kei-ito/esifycss#79]
Hi,
i am working on reducing my dependencies :)

this package still has a sub dependency on acorn < 7.1.1
in [this issue](https://github.com/kesne/acorn-dynamic-import/issues/22) of acorn-dynamic-import it states that the acorn supports dynamic imports itself.

Would it be possible to replace this dependency with the acorn internal stuff?

best regards

**Comment by kei-ito** [comment]
I heard it from you. The PR #80 will fix it. Thank you!

**Comment by TheGreatRefrigerator** [comment]
Wow that was fast.
thanks a lot 🎉

**Comment by TheGreatRefrigerator** [comment]
closed by https://github.com/kei-ito/esifycss/commit/62a689240702a3ecab90fa4b185138915a8ae11c

**Comment by kei-ito** [comment]
v1.4.18 was published to npm.

**Comment by kei-ito** [comment]
I found esifycss@1.4.18 crushes if a code has dynamic import statements.

**Comment by kei-ito** [comment]
I've published v1.4.19 that fixes the bug and marked v1.4.18 as deprecated.
